### ISSUE TITLE
searchDecoration not support prefixIcon color

### ISSUE THREAD

**Issue by primemb** [imtoori/CountryCodePicker#102]
Hi,
searchDecoration not support prefixIcon color.
I checked the code and understand on "selection_dialog" line 35 you are using this code to add search icon

`this.searchDecoration =searchDecoration.copyWith(prefixIcon: Icon(Icons.search)),`

so this code overlap user prefixIcon options.

I can make a pull request for this if you think this should change.

**Comment by vlfr1997** [comment]
Would be great if we could change this icon and the close icon too.

**Comment by imtoori** [comment]
this is fixed in the latest release
