### ISSUE TITLE
Dependency issue (modal_bottom_sheet)

### ISSUE THREAD

**Issue by kaboc** [imtoori/CountryCodePicker#106]
The modal_bottom_sheet package is now v0.2.2, but country_code_picker v1.5.0 depends on modal_bottom_sheet v0.2.0 specifically. This causes the following dependency issue if your app depends on modal_bottom_sheet v0.2.2.

```
Because my_app depends on country_code_picker ^1.5.0 which depends on modal_bottom_sheet 0.2.0, modal_bottom_sheet 0.2.0 is required.
So, because my_app depends on modal_bottom_sheet ^0.2.2, version solving failed.
pub get failed (1; So, because my_app depends on modal_bottom_sheet ^0.2.2, version solving failed.)
```

**Comment by joaowd** [comment]
I'm having the same issue

**Comment by joaowd** [comment]
Any update on this ?

**Comment by imtoori** [comment]
just merged a pr that fixes this problem
