### ISSUE TITLE
Extra background white color comes

### ISSUE THREAD

**Issue by pavelsust** [imtoori/CountryCodePicker#107]
Today when I install this library in my project i saw extra white color shadow in the background. How I can remove it?

![device-2020-09-25-154038](https://user-images.githubusercontent.com/7562445/94252273-835da480-ff45-11ea-8730-1053888e7d9b.png)

**Comment by jamesmoore255** [comment]
Same issue with me, it's not taking up any theme colors.

**Comment by emmaxCreative** [comment]
same problem. anyone knows a fix ?

**Comment by larssn** [comment]
@emmaxCreative We ended up using another package `country_pickers` which is very similar.

**Comment by Maxmontgelas** [comment]
Thanks for that, rather silly not catering for that.

**Comment by Maxmontgelas** [comment]
I forgot to never trust what I read on here...

boxDecoration: new BoxDecoration(
                              borderRadius: new BorderRadius.circular(16.0),
                              color: Colors.green,
                            ),

**Comment by pavelsust** [comment]
any one solve it yet??

**Comment by Maxmontgelas** [comment]
> any one solve it yet??

Nothing to solve.

**Comment by imtoori** [comment]
Hello everyone
I think this is a problem due to modal_bottom_sheet
https://github.com/jamesblasco/modal_bottom_sheet/issues/93
I'm trying to understand how to solve it
sorry for the delay

**Comment by pavelsust** [comment]
hello anyone solves it?

**Comment by imtoori** [comment]
closing this 
feel free to reopen it if you're still having issues

**Comment by DennisMuchiri** [comment]
Anyone looking for the solution:
barrierColor: Colors.transparent
