### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by karimkhaled1** [imtoori/CountryCodePicker#113]
How can i add new language to the package?
i have tried adding "ar" at isSupported and added ar.json file .

add gives me "A CountryLocalizations delegate that supports the ar locale was not found."

**Comment by imtoori** [comment]
you can open a pr to add the language 
https://github.com/imtoori/CountryCodePicker/pull/81/files
look at this to see an example

**Comment by Inassdev** [comment]
anything new about arabic language ?
