### ISSUE TITLE
No "send data back" function when using the countryBuilder

### ISSUE THREAD

**Issue by Simeon-5** [imtoori/CountryCodePicker#114]
I am using the latest version as of now 1.0.1+2.
When i use this code here: 
`  countryBuilder: (context, e) {
                            return Container(
                              height: 50,
                              color:
                                  ThemeBuilder.of(context).getCurrentTheme() ==
                                          Brightness.dark
                                      ? null
                                      : Colors.white,
                              child: Material(
                                color: Colors.transparent,
                                child: ListTile(
                                  leading: Image.asset(
                                    e.flagUri,
                                    package: 'country_list_pick',
                                    width: 30.0,
                                  ),
                                  title: Text(
                                    e.name,
                                    style: TextStyle(
                                      color: ThemeBuilder.of(context)
                                                  .getCurrentTheme() ==
                                              Brightness.dark
                                          ? Colors.black
                                          : Colors.white,
                                    ),
                                  ),
                                  onTap: () {
                                    //    _sendDataBack(context, e);
                                  },
                                ),
                              ),
                            );
                          },`

The tiles do not respond to touch and the selection doesnt change.

**Comment by imtoori** [comment]
@Simeon-5 I'm sorry but the latest version is 1.6.1
