### ISSUE TITLE
No support for dark theme

### ISSUE THREAD

**Issue by neelayak** [imtoori/CountryCodePicker#115]
I am trying the app in a dark theme and the text turned white and with white background text is not visible
`CountryCodePicker(
                        onChanged: (code) => print(
                            "on init ${code.name} ${code.dialCode} ${code.name}"),
                        // Initial selection and favorite can be one of code ('IT') OR dial_code('+39')
                        initialSelection: 'IN',
                        //  favorite: ['+39','FR'],
                        // optional. Shows only country name and flag
                        showCountryOnly: false,
                        // optional. Shows only country name and flag when popup is closed.
                        showOnlyCountryWhenClosed: false,
                        // optional. aligns the flag and the Text left
                        alignLeft: false,
                       // searchStyle: newTextTheme,
                        searchStyle: TextStyle(color: Colors.black),
                      ),`

**Comment by jacopofranza** [comment]
same problem here
