### ISSUE TITLE
dialogSize property does not effect width on flutter for web

### ISSUE THREAD

**Issue by ali-raza-flutter** [imtoori/CountryCodePicker#120]
@imtoori  dialogSize property only changes the height, it does not change the width on flutter web.

It's a Material Modal Bottom Sheet's issue,
If you wrap SelectionDialog in Center Widget that fixes the issue

_Originally posted by @ali-raza-flutter in https://github.com/imtoori/CountryCodePicker/issues/59#issuecomment-717760133_

**Comment by imtoori** [comment]
Thanks for the heads up
For the next time consider opening a pull request :) 
it would be nice both for you and the maintainer of the project

**Comment by ali-raza-flutter** [comment]
Thanks for the quick response.
I will keep that in mind 👍
