### ISSUE TITLE
Aliases for every option in country code picker

### ISSUE THREAD

**Issue by predatorx7** [imtoori/CountryCodePicker#122]
Can there be multiple aliases for a country when searching? i.e country's English name, country's name in local language, country's name in local language transliterated in English.
For example, if I search for Bhaarat, India, or भारत then the result should be 🇮🇳 भारत (or english name).

**Comment by imtoori** [comment]
This is available in the latest release!
You can check the translation jsons
Some codes have a list of strings and they will be used for searching
