### ISSUE TITLE
Order to show the countries

### ISSUE THREAD

**Issue by Ros4111** [imtoori/CountryCodePicker#123]
The only order is by the alphabetical english name of the country. This does not always match how it appears on the screen like in the next example:
 I would like to put my personalize order or the orders by how you see names on the screen.

![Screenshot_20201105-115031](https://user-images.githubusercontent.com/60907651/98231992-67deb400-1f5d-11eb-88aa-76a0c987c084.jpg)

Thanks so much. Great work.

**Comment by imtoori** [comment]
you can do this using CountryCodePicker.comparator
