### ISSUE TITLE
how to get length of phone Number after selection country Code .

### ISSUE THREAD

**Issue by nikhiladmin** [imtoori/CountryCodePicker#126]
I need to know what is the length of phone number in when i selected dialcode .

**Comment by hacmak18** [comment]
you can write that logic at onChange property.

**Comment by nikhiladmin** [comment]
I want to know the length of phone number when user select the country code because every country have different length of phone numbers so that how can I can verify entered phone number length . If  I don't no the length of phone number how can I compare in onChange property.

**Comment by imtoori** [comment]
I didn't understand why you can't do it in the onChange callback

**Comment by imtoori** [comment]
closing this
feel free to reopen it
