### ISSUE TITLE
Wrong Country Name

### ISSUE THREAD

**Issue by AsimBhadra** [imtoori/CountryCodePicker#136]
Its a small typo For Nepal it should be नेपाल and I think it should be Nepal rather than in Nepali text for easier search.

**Comment by imtoori** [comment]
can you elaborate more, please?

**Comment by AsimBhadra** [comment]
In Country Picker drop down list while searching for 'Nepal' we don't get any results as its written in Devanagari script that too is wrong. As many people don't use Devanagari script you cannot search for Nepal through standard keyboard.
![image](https://user-images.githubusercontent.com/38235601/115181274-3e72a880-a0f7-11eb-8e6c-f003a3e429fa.png)

When I search through country code
![image](https://user-images.githubusercontent.com/38235601/115181303-50ece200-a0f7-11eb-9f9a-61e56d1d1307.png)

We have to search in Devanagari script to find country which is hard by itself also its wrong it should be नेपाल instead of नपल .

**Comment by imtoori** [comment]
hi and sorry for the delay
By default the name of the countries are shown in their own language, I think you can try using English and it would be translated
