### ISSUE TITLE
while tapping "US" from dialog picker selects Canada as  a selected country.

### ISSUE THREAD

**Issue by DhrumilShah11** [imtoori/CountryCodePicker#141]
To Reproduce:
1> open country dialogue 
2> Type "us" into search fields
3> Then Select the USA from list..

after this steps you will get "Canada" as a selected country, for the first time after initialising country picker. can you please guide me ?

**Comment by imtoori** [comment]
it's not happening for me
can you check with the latest release?

**Comment by DhrumilShah11** [comment]
Thank you @imtoori ..but the latest version is forcing me to upgrade the current dart SDK. which is not feasible for me at present.

**Comment by NuteIla** [comment]
I am having the same problem, following thread.

**Comment by imtoori** [comment]
I'd be really happy to solve this issue, but I can't reproduce it
Can you give me more info?
