### ISSUE TITLE
Countries that presented in modal aren't presented in CountryManager

### ISSUE THREAD

**Issue by Veargan** [imtoori/CountryCodePicker#143]
These countries are presented in view. but aren't accessible via CountryManager();
+672 Antarctica
+47 Bouvet Island
+262 French Southern Territories
+0 Heard Island and Macdonald Islands
+599 Netherlands Antilles
+64 Pitcairn
+500 South Georgia and the South Sandwich Islands

For example +672 Antarctica:
onChanged callback returns country code 'AQ'
then calling
`CountryManager().countries.firstWhere((element) => element.countryCode == 'AQ', orElse: () => null)`
returns null

the same goes for another countries in the list above.

**Comment by Veargan** [comment]
Any updates?

**Comment by imtoori** [comment]
Hi @Veargan and sorry for the delay
The package does not contain any CountryManager class
Can you elaborate more?
