### ISSUE TITLE
Arabic language not showing properly

### ISSUE THREAD

**Issue by AminFadul** [imtoori/CountryCodePicker#19]
I'm using the latest version and on flutter stable channel

the arabic language is not showing on the dialog properly like showing on the picture 

this is on the iOS version 

don't know if it is the same for Android 

like you can see it's displaying the characters separated 

<img width="332" alt="Screenshot 2019-03-12 21 14 08" src="https://user-images.githubusercontent.com/29886596/54225144-1a9e0b00-450c-11e9-8aa6-829a5d029163.png">

<img width="265" alt="Screenshot 2019-03-12 21 14 22" src="https://user-images.githubusercontent.com/29886596/54225153-1f62bf00-450c-11e9-9482-565c2a368bda.png">

UAE -> should be "دولة اللإمارت العربية المتحدة" not  " د و ل ة ا ل ا ل إ م ا ر ا ت ا ل ع ر ب ي ة ا ل م ت ح د ة"
YMEN -> should be "اليمن" not "ا ل ي م ن"
and same goes for all the arabic countries 

also it is not working on typing too! 

<img width="362" alt="Screenshot 2019-03-12 21 24 53" src="https://user-images.githubusercontent.com/29886596/54225760-71581480-450d-11e9-953f-fde8243e3f9c.png">

one more issues that I found that it make my hole arabic langue messed up
after selecting an arabic country

<img width="345" alt="Screenshot 2019-03-12 21 35 41" src="https://user-images.githubusercontent.com/29886596/54226412-d95b2a80-450e-11e9-9e13-4d38615159a7.png">

**Comment by sam192011** [comment]
Is there a way to set every name in english only?

**Comment by sam192011** [comment]
the onChange callback return the name in the country's local language but does not accept that same name as a valid input.

**Comment by imtoori** [comment]
Hello,

I merged the pr, but I made an error because the list was modified and I didn't see that coming.
Anyway, do you have any idea? Do you think the right way is to translate anything to english by default?

**Comment by imtoori** [comment]
Added i18n
I think that should be enough
