### ISSUE TITLE
SelectionDialog has a long wait time

### ISSUE THREAD

**Issue by Afulton11** [imtoori/CountryCodePicker#23]
Using an iPhone 6 (real device), The SelectionDialog takes a very long time to show up (sometimes 10 seconds). I thought this might have to do with the way you are building the dialog and it does.

I replaced the current building to use a ListView instead of columns.

Here's what the SelectionDialog build function looks like now:

```dart
  @override
  Widget build(BuildContext context) {
    return SimpleDialog(
      title: Column(
        children: <Widget>[
          TextField(
            decoration: const InputDecoration(prefixIcon: Icon(Icons.search)),
            onChanged: _filterElements,
          ),
        ],
      ),
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: ListView(
            children: [
          widget.favoriteElements.isEmpty
              ? const BoxDecoration()
              : Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[]
                    ..addAll(widget.favoriteElements
                        .map(
                          (f) => SimpleDialogOption(
                                child: _buildOption(f),
                                onPressed: () {
                                  _selectItem(f);
                                },
                              ),
                        )
                        .toList())
                    ..add(const Divider())),
          
        ]..addAll(filteredElements.isEmpty
            ? [Center(child: Text('No Country Found.'))]
            : filteredElements.map(
                  (e) => SimpleDialogOption(
                    key: Key(e.toLongString()),
                    child: _buildOption(e),
                    onPressed: () {
                      _selectItem(e);
                    },
                  ),
                ).toList()
            ),
          ),
        ),
      ]
    );
  }

```

This drastically improved the wait time, but it still is taking a second at most to load the view. Using the `country_pickers` flutter package the wait time for the dialog to show is nearly non-existent on the same iPhone 6, but I like this package's widgets a lot more.

Also, please don't over-use the `new` keyword and use `const` everywhere possible.

**Comment by Afulton11** [comment]
I'll make a quick PR with a few improvements to the selection dialog widget.

**Comment by CodeGather** [comment]
More project requirements, text needs flexible layout and removal of national icons. I hope it can be improved to customize. Some of the codes I modified are as follows:

`Align(
      alignment: widget.alignments,
      child: Text(
          widget.showCountryOnly ? selectedItem.toCountryStringOnly() : selectedItem.toString(),
          style: widget.textStyle ?? Theme.of(context).textTheme.button,
      ),
),`

**Comment by imtoori** [comment]
@CodeGather could you make a mr or open an issue? Thank you 👍
