### ISSUE TITLE
Can't call setState on onChanged function 

### ISSUE THREAD

**Issue by freitzzz** [imtoori/CountryCodePicker#26]
`onChanged` function is called during CountryCodePicker state initialization, is there a particular reason for it? 

As it's called on initState I can't pass a function that calls my widget setState, as it will try to build my widget while CountryCodePicker widget is being initialized

**Comment by larssn** [comment]
Agreed, the widget should not trigger onChanged unless the _user actively selects a country_.

**Comment by freitzzz** [comment]
Hi @larssn !

Thanks for noticing the issue and also for reminding me that I still have this bug on the applicaton I'm currently working on!

Will keep your workaround in mind :)

**Comment by imtoori** [comment]
It should be ok now, can you give me feedback?
