### ISSUE TITLE
No country code

### ISSUE THREAD

**Issue by FilipeOS** [imtoori/CountryCodePicker#27]
Hi,

How can I show a drop down with the flag and country name without the phone indicative?

This is very important please

**Comment by imtoori** [comment]
Hello, there is a property called `showCountryOnly`. It should be ok.
Let me know

**Comment by FilipeOS** [comment]
Thank you.

How can I show the flag of a country? For example I use your package to save on the firebase the country code, how can I read it = show the flag of for example "en"?
