### ISSUE TITLE
Design issues and Overflow

### ISSUE THREAD

**Issue by FilipeOS** [imtoori/CountryCodePicker#34]
Hi,

Can you please adapt your code?

1. Can we have the option to remove the bold text when we show Flag+Country Name or whatever?

2. Flags size are different;

3. Can we have the option to change the padding? The actual option don't work;

4. When I have Flag+Country Name and something else on the left size (like icon or whatever), the countries with big name get overflow/error. Can they please go Flexible/Multiple lines?

All the above should be easy. THANK YOU for this awesome lib.

**Comment by FilipeOS** [comment]
Also please make the possibility to disable the touch because we can use it to read-only from database using country code, this is important.

Thanks you @imtoori !

**Comment by imtoori** [comment]
I've been busy, but now I'm trying to keep up.
I'll address this issue asap. Thank you :)

**Comment by imtoori** [comment]
1. There is the property `TextStyle`
2. I'll need to take a look
3. It does work, maybe there is some other problem
4. Added the property `textOverflow`
5. Added the property `enabled`. Set it to false to have it read-only

**Comment by KrisjanisE** [comment]
Hi,
the ```enabled``` property is ignored if property ```builder``` is used. If that's intentional, how to enable read-only wile using ```builder```?
