### ISSUE TITLE
How can I access the initialSelection or selectedItem?

### ISSUE THREAD

**Issue by ryankauk** [imtoori/CountryCodePicker#37]
Hey I'm fairly new to flutter so please excuse if this is a simple resolve. I use Localizations.localeOf(context).countryCode; to get the initial country code that I pass to your package. Your package builds the elements and converts this country code to a dialCode, but I need to access the initialSelection dialCode. How can I do this?

**Comment by animehacker** [comment]
Your question doesn't sound right. You said the countrycode is converted to a dialcode but you need the initialSelection dialcode. If you mean you need the selectedItem's country code you can do the following:

onChanged: (countryCode) {print(countryCode.name.toString()); }

So where I am printing the countryCode.name.toString() value you can pretty much do anything you want with the value at that point. The author of this package doesn't make it very clear to Flutter beginners how to do this so it took me a few minutes to come up with the above method.

Hopefully writing the solution here will help others.

If you really wanted the initialSelection dialCode then you could try assigning the value inside initState() e.g. initialDIalCode = widget.initialSelection.toString()

where:

final ValueChanged<String> initialDialCode;

This is just a rough guess as to how you could do that based on my observations of the country_code_picker class behavior.

**Comment by ranganaperera** [comment]
Currently the package doesn't support this functionality @ryankauk. As @animehacker has rightly mentioned you can delve into the country_code_picker class initState() and tweak the code a little. I have exposed a function to get these information as 'getInitialData'.

Check it out: https://github.com/ranganaperera/CountryCodePicker

**Comment by imtoori** [comment]
It's possible right now! I'll update the docs, but I added a property called `onInit` that will do the trick
