### ISSUE TITLE
icon cant display

### ISSUE THREAD

**Issue by DavidMGT** [imtoori/CountryCodePicker#43]
════════ (34) Exception caught by image resource service ═══════════════════════════════════════════
Unable to load asset: packages/country_code_picker/flags/im.png
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (35) Exception caught by image resource service ═══════════════════════════════════════════
Unable to load asset: packages/country_code_picker/flags/il.png
  ##═══════════════════════════════════════════════════
![屏幕快照 2019-09-20 下午7 13 34](https://user-images.githubusercontent.com/12042191/65323038-ebfb9e00-dbda-11e9-910e-5cef3624dec5.png)
═════════════════════════════════════════════════[](url)

**Comment by imranaalam** [comment]
same problem here.. what is the solution?

**Comment by imranaalam** [comment]
refresh the app.
pub get again
make sure it's in dependencies.

**Comment by imtoori** [comment]
thanks @imranaalam 
I was going to test it, but I think sometimes pub has some problems with dependencies
