### ISSUE TITLE
Uniform special characters for search

### ISSUE THREAD

**Issue by jamesmoore255** [imtoori/CountryCodePicker#48]
I had an issue searching for Mexico, as I have the US keyboard layout I don't have the é. I had to search with the tilde for it to show up. Is there anyway to ignore special characters on the search function?

**Comment by themobilecoder** [comment]
I am not sure if this is intended or a bug. I noticed that the filtered elements in the code are not localized first before being passed to the dialog. So when we type a text in the filter box, it still compares it with the unlocalized name of the country code.
