### ISSUE TITLE
why do not show default country when keyboard is not showing?

### ISSUE THREAD

**Issue by bianxiang** [imtoori/CountryCodePicker#49]
why do not show default country when keyboard is not showing?

**Comment by imtoori** [comment]
Do you mean getting it from the phone number of the running phone?

**Comment by bianxiang** [comment]
TextFormField(
                          validator: (String value) {
                            if (value.length == 0) {
                              return FlutterI18n.translate(
                                  context, '手机不能为空');
                            }
                            return null;
                          },
                          keyboardType: TextInputType.emailAddress,
                          controller: emailController,
                          decoration: InputDecoration(
                              focusedBorder: UnderlineInputBorder(
                                borderSide: BorderSide(color: Constant.MAIN_COLOR),
                              ),
                              border: UnderlineInputBorder(
                                  borderSide: BorderSide(color: Colors.grey[300])),
                              hintText: FlutterI18n.translate(
                                  context, '请输入手机号'),
                              prefix: CountryCodePicker(
                                onChanged: print,
                                initialSelection: '+86',
                                favorite: ['+86','CN'],


                              ),
                              hintStyle: Constant.INPUT_HINT_STYLE))



I changed "prefix" to "prefixIcon", it worked.

**Comment by bianxiang** [comment]
Do you mean getting it from the phone number of the running phone?

==>

It is also a good idea! You can set a property to show or hide phone number country!
