### ISSUE TITLE
On iPhone8plus,it can not show all of the country number！

### ISSUE THREAD

**Issue by bianxiang** [imtoori/CountryCodePicker#50]
On iPhone8plus,it can not show all of the country number！

[There is the bug video！](https://h5.weishi.qq.com/weishi/feed/6YztREcmm1IHpDvPU/wsfeed?wxplay=1&id=6YztREcmm1IHpDvPU&spid=1523352878705866&qua=v1_iph_weishi_6.2.6_322_app_a&chid=100081014&pkg=3670&attach=cp_reserves3_1000370011)

**Comment by imtoori** [comment]
Fixed with the latest release :) Sorry for the delay
