### ISSUE TITLE
option to set flag size and padding around flag element

### ISSUE THREAD

**Issue by yuhao-nyc** [imtoori/CountryCodePicker#54]
maybe I'm missing something. but is there anyway to set flag sizes and paddings on my own?

<img width="73" alt="Screenshot 2020-02-25 at 11 42 56 AM" src="https://user-images.githubusercontent.com/4121735/75267231-fb06fd80-57c3-11ea-9d2f-10344c4fd2b8.png">

Also. In the image above. I put the `CountryCodePicker` inside a `Flexible` widget it shrink automatically which is weird. any way to avoid this?

**Comment by imtoori** [comment]
I just added a property called `flagWidth`
Let me know if that solves your problem
