### ISSUE TITLE
Add Utility to Convert Country Code to Country Name

### ISSUE THREAD

**Issue by andrewjallenuoft** [imtoori/CountryCodePicker#55]
I am in the process of switching my app over from another country code picker library. One feature that library has which would be useful in this one is the ability to convert a country code to the country's name. 

For example, in the other library:

CountryPickerUtils.getCountryByIsoCode("GB") -> returns "United Kingdom"

**Comment by imtoori** [comment]
I just added a factory constructor `CountryCode.fromCode`

eg `CountryCode.fromCode('GB')`
