### ISSUE TITLE
Png flags do not have the same height

### ISSUE THREAD

**Issue by fvisticot** [imtoori/CountryCodePicker#58]
By example Autralia and France do not have the same height

**Comment by michael-ottink** [comment]
Instead of using png's isn't it possible to use the native flag emoji's?

**Comment by imtoori** [comment]
hey @michael-ottink 
it's not, at the beginning this package was done with emojis, but there was some problem with iOS

**Comment by imtoori** [comment]
closing this one
Also, I just discovered the Australian flag it's just wider than a usual flag! Good to know
