### ISSUE TITLE
Dialog's max width, max height

### ISSUE THREAD

**Issue by Gintasz** [imtoori/CountryCodePicker#59]
Hey,
nice lib. It wound be great if you added a max width, max height properties for the dialog, because if it's used on desktop or web, a full screen dialog with such big empty spaces does not look nice.

Cheers

**Comment by imtoori** [comment]
I just added a size property, hope it will be enough :)

**Comment by ali-raza-flutter** [comment]
dialogSize property only changes the height, it does not change the width on flutter web.

It's a Material Modal Bottom Sheet's issue,
If you wrap SelectionDialog in Center Widget that fixes the issue
