### ISSUE TITLE
Country filter is not working properly

### ISSUE THREAD

**Issue by parmesh-shiroya** [imtoori/CountryCodePicker#62]
After adding `CountryLocalizations.delegate` it change the name.
But after that search not work as per new name.
Ex. Before translation "India" show as "भारत" 
so for select that i have to type in hindi. But after adding  `CountryLocalizations.delegate` It show as "India" but still i have to type "भारत" in hindi to select it.

![IMG_20200330_151413](https://user-images.githubusercontent.com/26069212/77899051-bfb38f00-7299-11ea-966a-6dc0a2e06a4e.jpg)
![IMG_20200330_151441](https://user-images.githubusercontent.com/26069212/77899055-c2ae7f80-7299-11ea-8e84-cb5833275a62.jpg)

**Comment by AhsanAyaz** [comment]
Thanks for reporting. I just faced the same.

**Comment by imtoori** [comment]
Hey, I think it's solved now. Thanks for reporting :)
