### ISSUE TITLE
onInit handler is not called on initialisation

### ISSUE THREAD

**Issue by kaboc** [imtoori/CountryCodePicker#68]
`onInit` is called from `didUpdateWidget()`, which is called only on rebuild, resulting in it not getting called on initialisation.

**Comment by imtoori** [comment]
I just tried the example, but it's working. It's called on initialization

**Comment by kaboc** [comment]
Here is the minimum code.

```dart
import 'package:flutter/material.dart';
import 'package:country_code_picker/country_code_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build');

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: CountryCodePicker(
            initialSelection: 'US',
            onInit: print,
          ),
        ),
      ),
    );
  }
}
```

If it is true that `onInit` is called on initialisation, it should prints "build" and then "+1", but actually it does only when "build" is output more than once by rebuilds as the results of hot reloads/restarts or of other causes.

---

Additionally, would you try the following code as well please? It does not print "didUpdateWidget", which means `didUpdateWidget` is not called on initialisation.
As this code does not depend on third party packages, you can run it on DartPad too.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  MyApp();

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    super.initState();
    print('initState');
  }

  @override
  void didUpdateWidget(MyApp oldWidget) {
    super.didUpdateWidget(oldWidget);
    print('didUpdateWidget');
  }

  @override
  Widget build(BuildContext context) {
    return const SizedBox.shrink();
  }
}
```

**Comment by imtoori** [comment]
I can swear that the minimum code part prints "+1"

Anyway I believe that there is a problem, I'll analyze it better

**Comment by imtoori** [comment]
#74 fixes this bug

**Comment by kaboc** [comment]
Thank you! 😄
