### ISSUE TITLE
Allow custom settings of FlatButton or builder with no InkWell

### ISSUE THREAD

**Issue by kaboc** [imtoori/CountryCodePicker#69]
There is no arguments to pass in the settings of `FlatButton` such as shape, border and elevation.

In addition, even if you use `builder`, the widget returned from the builder function is automatically wrapped with `InkWell`, preventing you from customising the handling of tap events.

I actually managed to make the ripple effect invisible by making `splashColor` and `highlightColor` transparent and wrap `InkWell` with another button, in an attempt to handle tap events on my own.
It achieved my desired look but with no more luck because there is no way of manually showing the picker dialog, as mentioned in #60.

**Comment by cielo** [comment]
+1 Those flutter apps which use Cupertino theme won't necessarily be using `Material` widgets, which is a requirement for `InkWell`.

**Comment by imtoori** [comment]
Do you think that using a `GestureDetector` would be enough?

**Comment by kaboc** [comment]
@imtoori 
I don't think it is enough. Replacing `InkWell` with `GestureDetector` removes the ripple effect and makes it easier for developers to wrap it with a custom button, but it does not resolve the issue unless there is some way to call `_showSelectionDialog()` from the button.

Below are some ideas I've come up with, but there may be better solutions.

- Adding the `key` argument to the constructor of `CountryCodePicker` so that methods in `_CountryCodePickerState` can be called from outside via the key passed in.
- Adding a new argument like `customBuilder` to enable the widget returned from its function to be used **as is** without being wrapped with `InkWell` nor `GestureDetector` and to show the picker dialog from there.

**Comment by imtoori** [comment]
With the last version I just did what it's written in your first point

**Comment by kaboc** [comment]
Great! I was using v3.7 being unaware of the new version.

**Comment by kaboc** [comment]
In that case, I'm fine personally with your idea of using `GestureDetector` although it does not seem like the best solution. Isn't it a breaking change for other developers who have been users since older versions?

It may be better to keep this issue open for a while to collect others' opinions/ideas.

**Comment by imtoori** [comment]
Closing this
feel free to reopen it if you're still having issues
