### ISSUE TITLE
Dial code of Cayman Islands is wrong

### ISSUE THREAD

**Issue by kaboc** [imtoori/CountryCodePicker#75]
I found a possibly unnecessary space in the dial code of Cayman Islands in `country_codes.dart`. There is a space between `+` and `345`.

```dart
{
  "name": "Cayman Islands",
  "code": "KY",
  "dial_code": "+ 345",
},
```

I chose to file an issue rather than make a PR because the removal of the space might affect existing apps that have used the exact dial codes as they are in the list.

**Comment by imtoori** [comment]
I just googled it and the actual code should be +1345
