### ISSUE TITLE
Allow us to wrap the country picker in any container

### ISSUE THREAD

**Issue by naiksan-1020** [imtoori/CountryCodePicker#79]
Currently it shows the dialog but if it let us wrap the widget in a bottom sheet dialog or any other container, would be awesome.

**Comment by Abdullah-Zakhoi** [comment]
@naiksan-1020  right, agree with you. 

I made a Pull request for it you could take a look [#99](https://github.com/imtoori/CountryCodePicker/pull/99)

**Comment by imtoori** [comment]
pr merged, I'll release a new version asap

I'm closing this issue, feel free to reopen it
