### ISSUE TITLE
For ios how to dismiss it

### ISSUE THREAD

**Issue by vishwesh-aubergine** [imtoori/CountryCodePicker#88]
how to dismiss picker in ios if it is opened once

**Comment by Abdullah-Zakhoi** [comment]
@vishwesh-aubergine  if you mean dismiss `Country Code Picker Dialog` when you open it just by click on black places or by click on `close icon` 

<img width="250" height="500" alt="Screen Shot 2020-08-04 at 2 55 03 PM" src="https://user-images.githubusercontent.com/66040295/89294957-eda24900-d668-11ea-9715-790aac45ac06.gif">
