### ISSUE TITLE
Allow onSaved form field method

### ISSUE THREAD

**Issue by ShohidulProgrammer** [imtoori/CountryCodePicker#91]
Allow onSaved form field method to save country code when the form will be submitted.

**Comment by Abdullah-Zakhoi** [comment]
@ShohidulProgrammer  could you provide some code to know what do you mean, please.

if you want to save a country code when you select one ... you could by take it from `onChanged` method of `CountryCodePicker` class

**Comment by imtoori** [comment]
thanks @Abdullah-Zakhoi
