### ISSUE TITLE
How to add title ?

### ISSUE THREAD

**Issue by naeem01234** [imtoori/CountryCodePicker#97]
how to add title to add in header e.g " Select Country Code"

**Comment by Abdullah-Zakhoi** [comment]
hey, @naeem01234  header for `Dialog` page you mean !!!

<a><img src="https://user-images.githubusercontent.com/66040295/89201118-b1fc7600-d5b9-11ea-84b7-eaaf64c68938.png" height="400" width="250" ></a> 

If so, you could change it inside the `SelectionDialog` class.

you could add in `build widget` inside `Column` this code... 

```
 Padding(
              padding: const EdgeInsets.all(8.0),
              child: Container(
                width: MediaQuery.of(context).size.width,
                child: Text(
                  'Country Code Picker',
                  textAlign: TextAlign.center,
                ),
              ),
            ),
```

and the result will be ...

<img width="250" height="500" alt="Screen Shot 2020-08-04 at 2 55 03 PM" src="https://user-images.githubusercontent.com/66040295/89291044-7ff31e80-d662-11ea-8a8e-458d6091ec88.png"> 


or you could play with it as you like.
