### ISSUE TITLE
Last item is clipped

### ISSUE THREAD

**Issue by yap-studios** [imtoori/CountryCodePicker#98]
Good day,

@imtoori, When you scroll all the way to the bottom of the list, the very last item is clipped. In this case, it's British Virgin Island. Please see the picture below.

```
country_code_picker: ^1.4.0
```

```
flutter: 1.17.1
```

![Screenshot_20200721_183448](https://user-images.githubusercontent.com/46919661/88081987-75745780-cb81-11ea-9403-7ae830d8f058.jpg)

**Comment by Abdullah-Zakhoi** [comment]
@yap-studios  if you could show us your code, then we could see if there is a problem and what is the reason!
